version: '3'
services:
  mysql_single_node:
    container_name: mysql_single_node
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - "3306:3306"
    volumes:
      - $PWD/conf/my.cnf:/etc/mysql/my.cnf

