server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML

logging:
  level:
    root: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lujiahao.mapper
  mapper-locations: classpath:mapper/*.xml

