version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181
    networks:
      self_network:
        ipv4_address: 172.25.0.2

  mysql_master:
    container_name: mysql_master
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - 3306:3306
    depends_on:
      - zookeeper
    volumes:
      - ./logs/mysql/master/log:/var/log/mysql
      - ./data/mysql/master/data:/var/lib/mysql
      - ./conf/mysql_master.cnf:/etc/my.cnf
    networks:
      self_network:
        ipv4_address: 172.25.0.4

  canal_server_1:
    container_name: canal_server_1
    image: canal/canal-server:v1.1.4
    ports:
      - 11111:11111
    volumes:
      - ./conf/canal_server_1/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./conf/canal_server_1/example/instance.properties:/home/admin/canal-server/conf/example/instance.properties
      - ./logs/canal_server_1:/home/admin/canal-server/logs
    depends_on:
      - zookeeper
      - mysql_master
    networks:
      self_network:
        ipv4_address: 172.25.0.6
  canal_server_2:
    container_name: canal_server_2
    image: canal/canal-server:v1.1.4
    ports:
      - 11113:11113
    volumes:
      - ./conf/canal_server_2/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./conf/canal_server_2/example/instance.properties:/home/admin/canal-server/conf/example/instance.properties
      - ./logs/canal_server_2:/home/admin/canal-server/logs
    depends_on:
      - zookeeper
      - mysql_master
    networks:
      self_network:
        ipv4_address: 172.25.0.7

networks:
  self_network:
    external:
      name: self_network