version: "3"
services:
  redis:
    container_name: tensquare_redis
    image: redis
    ports:
      - 6379:6379
    restart: always
#    volumes:
#      这里看情况是否要挂载
#      - ./conf/mysql/mysql_data:/var/lib/mysql
    networks:
      - tensquare


networks:
  tensquare:
    driver: bridge