version: '3.5'
services:
  #Service for nameserver
  rmqnamesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    environment:
      - -JAVA_OPT_EXT=-server -Xms128m -Xmx128m -Xmn128m
    volumes:
      - ./data/rmqnamesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      - rmq

  #Service for broker
  rmqbroker:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker
    links:
      - rmqnamesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - JAVA_OPT=${JAVA_OPT} -server -Xms512m -Xmx512m -Xmn256m -XX:PermSize=128m -XX:MaxPermSize=128m
    volumes:
      - ./data/rmqbroker/logs:/home/rocketmq/logs
      - ./data/rmqbroker/store:/home/rocketmq/store
      - ./conf/broker.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf
    networks:
      - rmq

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole-single
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      - rmq

networks:
  rmq:
    name: rmq
    driver: bridge
