version: '3'
services:
  elasticsearch:
    container_name: es_node1
    image: elasticsearch:5.6.11
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx256m"
    volumes:
      - es_data1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    container_name: kibana
    image: kibana:5.6.11
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
  logstash:
    container_name: logstash
    image: logstash:5.6.15
    # logstash 启动时使用的配置文件
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      # logstash 配文件位置
      - $PWD/logstash/conf.d/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "4560:4560"
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro:0.8.3
    ports:
      - "9001:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
volumes:
  es_data1:
    driver: local
