version: '3'
services:
  mysql_master:
    container_name: mysql_master
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3307:3306"
    links:
      - mysql_slave_01
    volumes:
      - ./data/mysql/master/log:/var/log/mysql
      - ./data/mysql/master/data:/var/lib/mysql
      - ./master/my.cnf:/etc/my.cnf

  mysql_slave_01:
    container_name: mysql_slave_01
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql/slave01/log:/var/log/mysql
      - ./data/mysql/slave01/data:/var/lib/mysql
      - ./slave01/my.cnf:/etc/my.cnf
