version: '3.5'
services:
  master:
    image: redis
    container_name: redis-master
    command: redis-server
    ports:
      - "6380:6379"
    networks:
      - redis_master_slave
  
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master
    networks:
      - redis_master_slave
  
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - "6382:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master
    networks:
      - redis_master_slave

networks:
  redis_master_slave:
    name: redis_master_slave
    driver: bridge
